export const GEMMA_CONFIG = {
  bosTokenId: 2,
  eosTokenId: 1,
  padTokenId: 0,
  vocabSize: 262_144,
  hiddenSize: 640,
  intermediateSize: 2048,
  numHiddenLayers: 18,
  numAttentionHeads: 4,
  numKeyValueHeads: 1,
  headDim: 256,
  rmsNormEps: 1e-6,
  queryPreAttnScalar: 256,
  ropeTheta: 1_000_000,
  ropeLocalBaseFreq: 10_000,
  layerTypes: [
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
  ],
} as const;
