export const LFM_CONFIG = {
  bosTokenId: 1,
  eosTokenId: 7,
  padTokenId: 0,
  vocabSize: 65_536,
  hiddenSize: 1024,
  intermediateSize: 4608,
  numHiddenLayers: 16,
  numAttentionHeads: 16,
  numKeyValueHeads: 8,
  headDim: 64,
  convCacheLength: 3,
  rmsNormEps: 1e-5,
  ropeTheta: 1_000_000,
  layerTypes: [
    "conv",
    "conv",
    "full_attention",
    "conv",
    "conv",
    "full_attention",
    "conv",
    "conv",
    "full_attention",
    "conv",
    "full_attention",
    "conv",
    "full_attention",
    "conv",
    "full_attention",
    "conv",
  ],
} as const;
