export const MAPLE_CONFIG = {
  bosTokenId: 151_643,
  eosTokenId: 151_645,
  padTokenId: 151_643,
  vocabSize: 151_936,
  hiddenSize: 2_048,
  intermediateSize: 4_096,
  moeIntermediateSize: 512,
  numHiddenLayers: 24,
  numAttentionHeads: 16,
  numKeyValueHeads: 4,
  headDim: 128,
  rmsNormEps: 1e-6,
  ropeTheta: 10_000,
  partialRotaryFactor: 0.5,
  slidingWindow: 512,
  numExperts: 256,
  numExpertsPerTok: 8,
  normTopkProb: true,
  layerTypes: [
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
    "sliding_attention",
    "sliding_attention",
    "sliding_attention",
    "full_attention",
  ],
  nopeOnGlobalAttention: true,
} as const;
